### ISSUE TITLE
Implement issues for documentation and repository enhancement

### ISSUE THREAD

**Issue by EddieTheCubeHead** [softgitron/potku-console#1]
**Issue**
Currently changing documentation and meta-issues (workflow and repository configuration) needs to go through bug reports or feature suggestions.

**User story**
As a contributor I can create issues regarding documentation and the repository specifically, so that issues are better organized

**Proposed solution**
Implement two issue templates: update-documentation and add-documentation, mirroring bugs and feature requests, but on documentation side. Implement an issue template for repository enhancements. Create corresponding labels.

**Alternative solutions**
1: Use bugfixes and feature requests instead of specific issue templates.
2: Create only one issue template for both changing and adding documentation and leave repository updates to use feature requests and bug fixes.

**Comment by joomakelastudent** [comment]
Approved by me
